### ISSUE TITLE
Change xlim and ylim independently for each channel when exporting a .wsp to flowJo.

### ISSUE THREAD

**Issue by jmeskas** [RGLab/flowWorkspace#236] opened 2018-01-11 20:20 UTC
I would like to open up a wsp file in flowJo that I exported from flowWorkspace with having the axes limits pre-set by me. I would imagine that I could do this along the lines of:

flowWorkspace.par.set("plotGate",list(xlim = c(0,6) ))

However, this is applied to all channels. Is there a way to send multiple axes limits? 

Also I noticed a bug in flowWorkspace. In the GatingSet_Methods.R script where you define the function .plotGate you have xlim set for both xlim and ylim (lines 1331-1332):

                      , xlim = flowWorkspace.par.get("plotGate")[["xlim"]]
                      , ylim = flowWorkspace.par.get("plotGate")[["xlim"]]

The second one should be [["ylim"]]

Thank you,
Justin

**Comment by mikejiang** [comment] 2018-01-11 20:29
Any reason for not using the latest viz tool `ggcyto` instead?

**Comment by jmeskas** [comment] 2018-01-11 22:18
No reason. I don't have any experience with ggcyto. But will it do what I am after? I want to export an axes formatted wsp file. Below is the style that I am currently using to do this. If ggcyto can do this for me, could you direct me to a particular section?

gs <- GatingSet(fs)
...
(loop this part)
add(gs, ...
recompute(gs)
...
GatingSet2flowJo(gs, output.path)

Thanks,
Justin

**Comment by mikejiang** [comment] 2018-01-11 22:25
I thought you were speaking about the visualization problem in R. Can you elaborate your issue?

**Comment by jmeskas** [comment] 2018-01-11 22:30
I would like to manually set xlim and ylim for each channel in a gating set. Then export it as a flowJo workspace. Therefore, when I open the .wsp in flowJo I would like to see the exact same scaling.

**Comment by mikejiang** [comment] 2018-01-11 22:57
This should have been posted in to `CytoML`, setting `plotGate` parameters in `flowWorkspace` only changes the way you visualize it in R and thus has no lasting effect to the `GatingSet` object you are exporting.
Regarding to axis limits when displaying it in flowJo, it is currently determined by `flowJo`
automatically (https://github.com/RGLab/CytoML/blob/trunk/R/GatingSet2flowJo.R#L363).
Can you post the example plots illustrating the problem you are having?(I don't have the `flowJo` instance yet so can't reproduce your issue )

**Comment by jmeskas** [comment] 2018-01-16 19:20
Hi Mike. I did as you suggested and created a post in CytoML. I was wondering if you could reply there. Please let me know if it is an easy task and that you will get to it soon, or if it is too much for you to do now. Maybe there is somewhere else I should be looking into? Thank you.

**Comment by mikejiang** [comment] 2018-01-16 19:46
closed by RGLab/CytoML#32

**Closed by mikejiang** 2018-01-16 19:46 UTC
